### ISSUE TITLE
App not Working

### ISSUE THREAD

**Issue by NestorDevs** [quietwar/food_app#1]
hello I made the whole app without cloning the git ... however, I skip error I have everything set up just like you but it tells me the error once I login...

On the other hand the registration buttons and create account and login are uninhabited even when the validators are met ... could you help me?
![photo5114083092414441477](https://user-images.githubusercontent.com/36705339/63553978-230e5f00-c50a-11e9-8126-7af2f7316517.jpg)

**Comment by NestorDevs** [comment]
I have the database created but without documents and when I login, shouldn't the users collection be created?

**Comment by quietwar** [comment]
Hi Nestor, sorry about that. I put this app on so someone else could fork it fix that error you are showing me. If they are able to fix it for me, I will update the repo and send ping you.
thank you
